#!name=Youtube Ad Block
#!desc=Youtube广告屏蔽
#!system=ios

[URL Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - reject-img

[Script]
youtube_request=type=http-request,requires-body=true,timeout=30,max-size=3145728,binary-mode=true,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence)\?,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.beta.js
youtube_response=type=http-response,requires-body=true,timeout=30,max-size=3145728,binary-mode=true,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting)\?,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.beta.js

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com